### ISSUE TITLE
f5name format for subnet ids

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/terraform-aws-f5-sca#10]
Change bigip map subnetID names to match the object names in the Declarative Onboarding declarations

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/understanding-the-json-schema.html?highlight=underscores

"application-region": {
            "class": "VLAN",
            "tag": 4093,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.2",
                    "tagged": false
                }
            ]
        },

Format Name | Matches/Validates
-- | --
f5name | Names allowed for properties in declarations: 1–64 characters, alphanumeric plus underscore (‘_’), starting with a letter. Letter-case is significant.

example:
        "us-west-1a:private:0" = {
          "device_index"      = "2"
          "interface_type"    = "private"
          "private_ips_count" = 0
          "public_ip"         = false
          "subnet_id"         = var.subnets.value.az1.security.**application_region**
          "subnet_security_group_ids" = [
            var.security_groups.value.private
          ]
        }

expected:
        "us-west-1a:private:0" = {
          "device_index"      = "2"
          "interface_type"    = "private"
          "private_ips_count" = 0
          "public_ip"         = false
          "subnet_id"         = var.subnets.value.az1.security.**application-region**
          "subnet_security_group_ids" = [
            var.security_groups.value.private
          ]
        }

**Comment by hparr** [comment]
Discussed and moving to feature.

**Comment by adam-f5** [comment]
Repository Archived
